### PR TITLE
include numeric for accumulate

### PR DESCRIPTION
**Pull request by mmurooka**
I confirmed that `warehouse_ros_sqlite` works in Ubuntu 18.04 / ROS Melodic with latest master branch of MoveIt. gcc version is 7.4.0. Need following fix.

1. Fix for the following error.
```
/home/leus/ws_moveit/src/warehouse_ros_sqlite/include/warehouse_ros_sqlite/client.h:332:17: error: ‘accumulate’ is not a member of ‘std’
     cmd += std::accumulate(std::begin(metastring), std::end(metastring), std::string(),
```

2. Use `std::unique_ptr` instead of `std::auto_ptr` to avoid the following warning (ref: https://stackoverflow.com/q/40893636 ). `std::unique_ptr` also is used in many places of moveit sources.
```
/home/leus/ws_moveit/src/warehouse_ros_sqlite/include/warehouse_ros_sqlite/client.h:343:8: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<DBClientCursor> query(const std::string ns, const sqlite::Query query)
        ^~~~~~~~
```

### CODE REVIEW

**Comment by k-okada** [comment]
Thanks !
Is this compatible with 16.04?

**Comment by mmurooka** [comment]
It should work, and I actually checked build passing and working in Ubuntu16.04 / ROS Kinetic environment.

BTW, joint space & cartesian path are planned from stored states in Ubuntu 18.04 + MoveIt master branch with this PR's warehosue_ros_sqlite and https://github.com/ros-planning/moveit/pull/932:
https://drive.google.com/file/d/1nTdJ5QrUq-Ah1jAasrhz8wWoIe0RWr6R/view?usp=sharing
I'd like this package to be available as standard in MoveIt!
